trigger: none

parameters:
- name: modules
  displayName: "Modules to fetch (comma-separated)"
  type: string
  default: "network,compute"
- name: azureReposName
  displayName: "Azure Repos repository name (created if missing)"
  type: string
  default: "demo-repos"

resources:
  repositories:
    - repository: terraform-modules
      type: github
      name: rachita2901/Terraform-templates
      endpoint: Kartavya0206
      ref: refs/heads/main

stages:
# Create Azure Repos repository if it doesn't exist (requires Build Service "Create repository" permission)
- stage: Create_Repo
  displayName: Create Azure Repos Repository (if needed)
  jobs:
  - job: CreateRepository
    displayName: Ensure repository exists
    pool:
      name: Windows-SelfHosted
      demands:
        - Agent.Name -equals testingvm
    steps:
    - powershell: |
        $orgUrl = "$(System.TeamFoundationCollectionUri)".TrimEnd('/')
        $projectName = "$(System.TeamProject)"
        $projectId = "$(System.TeamProjectId)"
        $repoName = "${{ parameters.azureReposName }}"
        $token = "$(System.AccessToken)"

        Write-Host "Organization: $orgUrl"
        Write-Host "Project: $projectName"
        Write-Host "Repository: $repoName"
        Write-Host ""

        $base64Token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))
        $headers = @{
          Authorization = "Basic $base64Token"
          "Content-Type" = "application/json"
        }

        Write-Host "Getting project details..."
        $projectUrl = "$orgUrl/_apis/projects/$projectId`?api-version=7.1"
        $project = Invoke-RestMethod -Uri $projectUrl -Headers $headers -Method Get
        Write-Host "✓ Project ID: $($project.id)"
        Write-Host ""

        Write-Host "Checking if repository '$repoName' exists..."
        $reposUrl = "$orgUrl/$projectName/_apis/git/repositories`?api-version=7.1"
        $repos = Invoke-RestMethod -Uri $reposUrl -Headers $headers -Method Get
        $existing = $repos.value | Where-Object { $_.name -eq $repoName }

        if ($existing) {
          Write-Host "✓ Repository '$repoName' already exists."
          exit 0
        }

        Write-Host "Repository not found. Creating new repository '$repoName'..."
        $createUrl = "$orgUrl/$projectName/_apis/git/repositories`?api-version=7.1"
        $body = @{
          name    = $repoName
          project = @{ id = $projectId }
        } | ConvertTo-Json

        Write-Host ""
        Write-Host "Request body:"
        Write-Host $body

        try {
          $newRepo = Invoke-RestMethod -Uri $createUrl -Headers $headers -Method Post -Body $body
          Write-Host "✓ Repository '$repoName' created successfully."
        } catch {
          Write-Error "Failed to create repository: $($_.Exception.Message)"
          if ($_.ErrorDetails.Message) { Write-Host $_.ErrorDetails.Message }
          exit 1
        }
      displayName: Create Azure Repos Repository (if needed)
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- stage: Fetch_Modules
  displayName: Fetch Selected Terraform Modules
  jobs:
  - job: Fetch
    displayName: Copy Selected Modules
    pool:
      name: Windows-SelfHosted
      demands:
        - Agent.Name -equals testingvm

    steps:
    - checkout: self
      persistCredentials: true
      displayName: Checkout Azure Repos

    - checkout: terraform-modules
      displayName: Checkout Terraform Modules Repo

    - powershell: |
        $modules = "${{ parameters.modules }}".Split(",")
        Write-Host "Modules to fetch: $($modules -join ', ')"

        $sourceRoot = "$(Build.SourcesDirectory)\Terraform-templates\modules"
        $destinationRoot = "$(Build.SourcesDirectory)\s\selected-modules"

        if (-not (Test-Path $sourceRoot)) {
            Write-Error "Modules directory not found at: $sourceRoot"
            exit 1
        }

        Write-Host "`nAvailable modules:"
        Get-ChildItem $sourceRoot -Directory | ForEach-Object { Write-Host "  - $($_.Name)" }

        # Create destination directory
        New-Item -ItemType Directory -Force -Path $destinationRoot | Out-Null

        $failedModules = @()
        $successModules = @()

        foreach ($module in $modules) {
          $module = $module.Trim()
          $sourcePath = Join-Path $sourceRoot $module
          $destinationPath = Join-Path $destinationRoot $module

          if (Test-Path $sourcePath) {
            Write-Host "`nCopying module: $module"
            Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
            $successModules += $module
          } else {
            Write-Warning "Module '$module' not found"
            $failedModules += $module
          }
        }

        Write-Host "`n=== Summary ==="
        Write-Host "Successfully copied: $($successModules.Count) module(s)"
        $successModules | ForEach-Object { Write-Host "  ✓ $_" }
        
        if ($failedModules.Count -gt 0) {
            Write-Host "`nFailed: $($failedModules.Count) module(s)"
            $failedModules | ForEach-Object { Write-Host "  ✗ $_" }
            Write-Error "Some modules not found"
            exit 1
        }

        Write-Host "`n✓ Modules copied successfully"
      displayName: Copy Selected Modules

    - powershell: |
        # Navigate to Azure Repos directory (self checkout)
        Set-Location "$(Build.SourcesDirectory)\s"
        
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Repository name: $(Build.Repository.Name)"

        # Configure Git
        git config user.email "azurepipeline@devops.com"
        git config user.name "Azure Pipeline Bot"

        # Get the Azure Repos URL with authentication token
        $orgUrl = "$(System.TeamFoundationCollectionUri)".TrimEnd('/')
        $project = "$(System.TeamProject)"
        $repoName = "$(Build.Repository.Name)"
        $token = "$(System.AccessToken)"
        
        # Encode the token for URL
        $base64Token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))
        $azureReposUrl = "$orgUrl/$project/_git/$repoName"
        
        Write-Host "Azure Repos URL: $azureReposUrl"

        # Set the remote to Azure Repos explicitly
        git remote set-url origin $azureReposUrl
        
        # Verify remote
        Write-Host "`nConfigured remote:"
        git remote -v

        # Create a unique branch name
        $branchName = "selected-modules-$(Build.BuildId)"
        $modulesParam = "${{ parameters.modules }}"
        
        Write-Host "`nCreating branch: $branchName"
        
        # Create and checkout new branch
        git checkout -b $branchName

        # Add the selected modules
        git add selected-modules/
        
        # Check if there are changes
        $status = git status --porcelain
        if ($status) {
            Write-Host "`nCommitting changes..."
            git commit -m "Pipeline: Added selected modules [$modulesParam]`n`nBuild ID: $(Build.BuildId)`nRequested modules: $modulesParam"
            
            Write-Host "`nPushing to Azure Repos..."
            
            # Use the -c credential helper to pass the token
            $env:GIT_ASKPASS = "echo"
            git -c http.extraheader="AUTHORIZATION: Basic $base64Token" push origin $branchName
            
            if ($LASTEXITCODE -eq 0) {
                Write-Host "`n✓ Successfully pushed to branch: $branchName" -ForegroundColor Green
                Write-Host "`nView in Azure Repos:"
                Write-Host "$azureReposUrl?version=GB$branchName&path=/selected-modules" -ForegroundColor Cyan
            } else {
                Write-Error "Failed to push to Azure Repos"
                exit 1
            }
        } else {
            Write-Host "No changes to commit"
        }
      displayName: Push to Azure Repos
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)