trigger: none

parameters:
- name: modules
  displayName: "Modules to fetch (comma-separated)"
  type: string
  default: "network,compute"

resources:
  repositories:
    - repository: terraform-modules
      type: github
      name: rachita2901/Terraform-templates
      endpoint: Kartavya0206
      ref: refs/heads/main

stages:
- stage: Fetch_Modules
  displayName: Fetch Selected Terraform Modules
  jobs:
  - job: Fetch
    displayName: Copy Selected Modules
    pool:
      name: Windows-SelfHosted
      demands:
        - Agent.Name -equals testingvm

    steps:
    - checkout: terraform-modules
      displayName: Checkout Terraform Modules

    - powershell: |
        $modules = "${{ parameters.modules }}".Split(",")
        Write-Host "Modules to fetch: $($modules -join ', ')"

        $sourceRoot = "$(Build.SourcesDirectory)\modules"
        $destinationRoot = "$(Build.SourcesDirectory)\selected-modules"

        if (-not (Test-Path $sourceRoot)) {
            Write-Error "Modules directory not found"
            exit 1
        }

        Write-Host "`n Available modules:"
        Get-ChildItem $sourceRoot -Directory | ForEach-Object { Write-Host "  - $($_.Name)" }

        New-Item -ItemType Directory -Force -Path $destinationRoot | Out-Null

        foreach ($module in $modules) {
          $module = $module.Trim()
          $sourcePath = Join-Path $sourceRoot $module
          $destinationPath = Join-Path $destinationRoot $module

          if (Test-Path $sourcePath) {
            Write-Host "Copying module: $module"
            Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
          } else {
            Write-Error "Module '$module' not found"
            exit 1
          }
        }

        Write-Host "`n Modules copied successfully"
      displayName: Copy Selected Modules

    - powershell: |
        Set-Location "$(Build.SourcesDirectory)"
        
        Write-Host "Initializing Git repository..."
        git init
        
        git config user.email "pipeline@azuredevops.com"
        git config user.name "Azure Pipeline"
        
        # Use the repo where this pipeline runs (from pipeline context)
        $repoName = "$(Build.Repository.Name)"
        $baseUrl = "$(System.TeamFoundationCollectionUri)".TrimEnd('/')
        $projectName = "$(System.TeamProject)"
        $repoUrl = "$baseUrl/$projectName/_git/$repoName"
        
        Write-Host "Target repository: $repoName"
        Write-Host "Repository URL: $repoUrl"
        
        # Add remote
        git remote add origin $repoUrl
        
        # Create branch
        $branchName = "modules-$(Build.BuildId)"
        git checkout -b $branchName
        
        # Add files
        git add selected-modules/
        
        # Commit
        Write-Host "`nCommitting changes..."
        git commit -m "Pipeline Build $(Build.BuildId): Added modules ${{ parameters.modules }}"
        
        # Create auth token
        $token = "$(System.AccessToken)"
        $base64Token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))
        
        # Push
        Write-Host "`nPushing to Azure Repos..."
        git -c http.extraheader="AUTHORIZATION: Basic $base64Token" push origin $branchName
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "`n========================================" -ForegroundColor Green
            Write-Host " SUCCESS! " -ForegroundColor Green
            Write-Host "========================================" -ForegroundColor Green
            Write-Host "`nModules pushed to Azure Repos!" -ForegroundColor Cyan
            Write-Host "`nView your modules at:" -ForegroundColor Yellow
            Write-Host "$repoUrl`?version=GB$branchName&path=/selected-modules"
            Write-Host "`n========================================" -ForegroundColor Green
        } else {
            Write-Error "Push failed"
            exit 1
        }
      displayName: Push to Azure Repos
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)